name: Obtener licencia de Unity

on: workflow_dispatch

jobs:
  requestManualActivationFile:
    name: Solicitud de archivo de activación
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile
      
      - uses: actions/upload-artifacts@v2
        with: 
          name: Archivo de activación manual
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}